"""Numeric Traceability and Grounding Enforcement (P4).

Implements the strict numeric traceability check specified in Blueprint v2 §F.6 and §H:
Every numeric token in the Copilot's answer must trace to a tool-call result
or retrieved knowledge base passage from the current turn.
If any unsupported number is introduced, the response is downgraded to grounded: false.
"""

from typing import Any, List, Set, Union
import re
import json


def extract_numeric_tokens(text_or_obj: Union[str, Any]) -> Set[str]:
    """Extract normalized numeric tokens from text or JSON data structures."""
    if not isinstance(text_or_obj, str):
        text = json.dumps(text_or_obj)
    else:
        text = text_or_obj

    # Regex matches integer or floating point numbers (with optional signs or trailing %)
    pattern = r"[-+]?\b\d+(?:\.\d+)?%?\b"
    raw_tokens = re.findall(pattern, text)

    normalized: Set[str] = set()
    for tok in raw_tokens:
        clean = tok.rstrip("%")
        normalized.add(clean)
        try:
            val = float(clean)
            # Add formatted representations (e.g., 0.33 vs 0.330)
            normalized.add(f"{val:.1f}")
            normalized.add(f"{val:.2f}")
            normalized.add(f"{val:.3f}")
            normalized.add(f"{val:.4f}")
            if val.is_integer():
                normalized.add(str(int(val)))
        except ValueError:
            pass

    return normalized


def verify_numeric_grounding(
    answer: str,
    context_sources: List[Union[str, Any]],
) -> bool:
    """Verify that every numeric token in answer is supported by context_sources.
    
    Args:
        answer: The text generated by the Copilot.
        context_sources: List of retrieved text chunks or tool result dictionaries.
        
    Returns:
        True if all numeric tokens trace back to context; False otherwise.
    """
    answer_numbers = extract_numeric_tokens(answer)
    if not answer_numbers:
        # If no numeric claims are made, the response has no ungrounded numbers
        return True

    # Pool all numbers from context sources
    source_numbers: Set[str] = set()
    for source in context_sources:
        source_numbers.update(extract_numeric_tokens(source))

    # Common innocent numbers / dates that don't need strict verification (e.g. single digits like 1, 2)
    whitelisted = {"1", "2", "3", "4"}

    unsupported = []
    for num in answer_numbers:
        if num in whitelisted:
            continue
        if num not in source_numbers:
            unsupported.append(num)

    return len(unsupported) == 0
