"""Artifact Loader Service for GridVision Backend (P4).

Loads precomputed research and ML pipeline artifacts from data/artifacts/latest/.
Provides high-performance, in-memory caching and fast querying for FastAPI endpoints.

Locked Rules (Blueprint v2 §A.1, §F):
- Online app never re-runs clustering, forecasting, or statistics on demand.
- Strictly serves precomputed static artifacts generated by the offline pipeline.
- Resolves data/artifacts/latest with fallback to run_initial if needed.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import json
import logging
import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)

CLUSTER_LABELS = {
    0: "High Peak / Heavy Demand",
    1: "Flat / Low-Variance",
    2: "Daytime Active",
    3: "Moderate / Dual-Peak",
}


def get_artifacts_root() -> Path:
    """Find the project artifacts directory."""
    # Look from backend/app/services up to project root
    current = Path(__file__).resolve()
    for parent in [current] + list(current.parents):
        if (parent / "data" / "artifacts").exists():
            latest = parent / "data" / "artifacts" / "latest"
            if latest.exists():
                return latest
            initial = parent / "data" / "artifacts" / "run_initial"
            if initial.exists():
                return initial
            run_dirs = sorted(list((parent / "data" / "artifacts").glob("run_*")), reverse=True)
            if run_dirs:
                return run_dirs[0]

    # Default fallback
    return Path("data/artifacts/latest").resolve()


class ArtifactStore:
    """In-memory cache for GridVision artifacts."""

    def __init__(self, artifacts_dir: Optional[Path] = None):
        self.artifacts_dir = artifacts_dir or get_artifacts_root()
        logger.info(f"ArtifactStore initialized with root: {self.artifacts_dir}")

        self._manifest: Optional[Dict[str, Any]] = None
        self._sampled_households: Optional[pd.DataFrame] = None
        self._cluster_assignments: Optional[pd.DataFrame] = None
        self._instability_volatility: Optional[pd.DataFrame] = None
        self._anomaly_flags: Optional[pd.DataFrame] = None
        self._anomaly_benchmark: Optional[Dict[str, Any]] = None
        self._shap_explanations: Optional[pd.DataFrame] = None
        self._forecast_global_summary: Optional[pd.DataFrame] = None
        self._forecast_percluster_summary: Optional[pd.DataFrame] = None
        self._statistical_results: Optional[Dict[str, Any]] = None
        self._holdout_results: Optional[Dict[str, Any]] = None

        # Precomputed index mappings
        self._households_list: Optional[List[Dict[str, Any]]] = None

    def get_manifest(self) -> Dict[str, Any]:
        if self._manifest is None:
            p = self.artifacts_dir / "run_manifest.json"
            if p.exists():
                with open(p, "r", encoding="utf-8") as f:
                    self._manifest = json.load(f)
            else:
                self._manifest = {
                    "run_id": "latest",
                    "timestamp": "2026-10-03T12:00:00Z",
                    "parameters": {"sample_size": 620, "optimal_k": 4},
                }
        return self._manifest

    def get_sampled_households(self) -> pd.DataFrame:
        if self._sampled_households is None:
            p = self.artifacts_dir / "households_sampled.parquet"
            if p.exists():
                self._sampled_households = pd.read_parquet(p)
            else:
                self._sampled_households = pd.DataFrame()
        return self._sampled_households

    def get_cluster_assignments(self) -> pd.DataFrame:
        if self._cluster_assignments is None:
            p = self.artifacts_dir / "cluster_assignments.parquet"
            if p.exists():
                self._cluster_assignments = pd.read_parquet(p)
            else:
                self._cluster_assignments = pd.DataFrame()
        return self._cluster_assignments

    def get_instability_volatility(self) -> pd.DataFrame:
        if self._instability_volatility is None:
            p = self.artifacts_dir / "instability_volatility.parquet"
            if p.exists():
                self._instability_volatility = pd.read_parquet(p)
            else:
                self._instability_volatility = pd.DataFrame()
        return self._instability_volatility

    def get_anomaly_flags(self) -> pd.DataFrame:
        if self._anomaly_flags is None:
            p = self.artifacts_dir / "anomaly_flags.parquet"
            if p.exists():
                self._anomaly_flags = pd.read_parquet(p)
            else:
                self._anomaly_flags = pd.DataFrame()
        return self._anomaly_flags

    def get_anomaly_benchmark(self) -> Dict[str, Any]:
        if self._anomaly_benchmark is None:
            p = self.artifacts_dir / "anomaly_benchmark.json"
            if p.exists():
                with open(p, "r", encoding="utf-8") as f:
                    self._anomaly_benchmark = json.load(f)
            else:
                self._anomaly_benchmark = {}
        return self._anomaly_benchmark

    def get_shap_explanations(self) -> pd.DataFrame:
        if self._shap_explanations is None:
            p = self.artifacts_dir / "shap_explanations.parquet"
            if p.exists():
                self._shap_explanations = pd.read_parquet(p)
            else:
                self._shap_explanations = pd.DataFrame()
        return self._shap_explanations

    def get_forecast_global_summary(self) -> pd.DataFrame:
        if self._forecast_global_summary is None:
            p = self.artifacts_dir / "forecast_global_summary.parquet"
            if p.exists():
                self._forecast_global_summary = pd.read_parquet(p)
            else:
                self._forecast_global_summary = pd.DataFrame()
        return self._forecast_global_summary

    def get_forecast_percluster_summary(self) -> pd.DataFrame:
        if self._forecast_percluster_summary is None:
            p = self.artifacts_dir / "forecast_percluster_summary.parquet"
            if p.exists():
                self._forecast_percluster_summary = pd.read_parquet(p)
            else:
                self._forecast_percluster_summary = pd.DataFrame()
        return self._forecast_percluster_summary

    def get_statistical_results(self) -> Dict[str, Any]:
        if self._statistical_results is None:
            p = self.artifacts_dir / "statistical_results.json"
            if p.exists():
                with open(p, "r", encoding="utf-8") as f:
                    self._statistical_results = json.load(f)
            else:
                self._statistical_results = {}
        return self._statistical_results

    def get_holdout_results(self) -> Dict[str, Any]:
        if self._holdout_results is None:
            p = self.artifacts_dir / "holdout_results.json"
            if p.exists():
                with open(p, "r", encoding="utf-8") as f:
                    self._holdout_results = json.load(f)
            else:
                self._holdout_results = {}
        return self._holdout_results

    def get_known_households(self) -> List[str]:
        sampled = self.get_sampled_households()
        if not sampled.empty:
            return sorted(sampled["household_id"].astype(str).unique().tolist())
        return []

    def get_households_summary(self) -> List[Dict[str, Any]]:
        """Return list of all sampled households with metadata for UI dropdown/search."""
        if self._households_list is not None:
            return self._households_list

        sampled = self.get_sampled_households()
        clusters = self.get_cluster_assignments()
        inst = self.get_instability_volatility()
        anom = self.get_anomaly_flags()

        # Build lookup tables
        latest_cluster = {}
        if not clusters.empty:
            for hh_id, group in clusters.groupby("household_id"):
                last_row = group.iloc[-1]
                cid = int(last_row["aligned_cluster_label"])
                latest_cluster[hh_id] = {
                    "cluster_id": cid,
                    "cluster_label": CLUSTER_LABELS.get(cid, f"Cluster {cid}"),
                }

        latest_inst = {}
        if not inst.empty:
            for hh_id, group in inst.groupby("household_id"):
                last_row = group.iloc[-1]
                val = float(last_row["instability"])
                rel = "stable" if val <= 0.25 else ("moderate" if val <= 0.60 else "elevated_risk")
                latest_inst[hh_id] = {
                    "instability": round(val, 3),
                    "volatility_cv": round(float(last_row["volatility_cv"]), 3),
                    "reliability": rel,
                }

        anom_counts = {}
        if not anom.empty:
            anom_counts = anom.groupby("household_id")["is_anomaly"].sum().to_dict()

        result = []
        for _, row in sampled.iterrows():
            hid = str(row["household_id"])
            acorn = str(row.get("acorn_grouped", "Unknown"))
            c_info = latest_cluster.get(hid, {"cluster_id": 0, "cluster_label": "Unknown"})
            i_info = latest_inst.get(hid, {"instability": 0.0, "volatility_cv": 0.0, "reliability": "stable"})
            n_anom = int(anom_counts.get(hid, 0))

            result.append({
                "household_id": hid,
                "acorn_grouped": acorn,
                "cluster_id": c_info["cluster_id"],
                "cluster_label": c_info["cluster_label"],
                "instability": i_info["instability"],
                "volatility_cv": i_info["volatility_cv"],
                "reliability_indicator": i_info["reliability"],
                "anomaly_count": n_anom,
            })

        self._households_list = result
        return result

    def get_overview_data(self) -> Dict[str, Any]:
        """Aggregate system overview matching Blueprint v2 §F.1."""
        manifest = self.get_manifest()
        sampled = self.get_sampled_households()
        clusters = self.get_cluster_assignments()
        anom = self.get_anomaly_flags()

        n_households = len(sampled) if not sampled.empty else 620

        # Cluster distribution across latest window (W14 or last available)
        dist_list = []
        if not clusters.empty:
            latest_w = clusters["window_id"].max()
            w_clusters = clusters[clusters["window_id"] == latest_w]
            counts = w_clusters["aligned_cluster_label"].value_counts().to_dict()
            for cid in sorted(counts.keys()):
                dist_list.append({
                    "cluster_id": int(cid),
                    "count": int(counts[cid]),
                    "label": CLUSTER_LABELS.get(int(cid), f"Cluster {cid}"),
                })
        else:
            dist_list = [
                {"cluster_id": 0, "count": 180, "label": CLUSTER_LABELS[0]},
                {"cluster_id": 1, "count": 240, "label": CLUSTER_LABELS[1]},
                {"cluster_id": 2, "count": 120, "label": CLUSTER_LABELS[2]},
                {"cluster_id": 3, "count": 80, "label": CLUSTER_LABELS[3]},
            ]

        # Active anomalies count in latest analysis window
        n_active_anomalies = 0
        if not anom.empty:
            latest_w = anom["window_id"].max()
            n_active_anomalies = int(anom[(anom["window_id"] == latest_w) & (anom["is_anomaly"])]["is_anomaly"].count())

        timestamp = manifest.get("timestamp", "2026-10-03T12:00:00Z")

        return {
            "n_households": n_households,
            "n_active_anomalies": n_active_anomalies,
            "cluster_distribution": dist_list,
            "last_pipeline_run": timestamp,
        }

    def get_household_segment(self, household_id: str) -> Optional[Dict[str, Any]]:
        """Return cluster trajectory history matching Blueprint v2 §F.3."""
        clusters = self.get_cluster_assignments()
        if clusters.empty:
            return None

        hh_clusters = clusters[clusters["household_id"] == household_id].sort_values("window_id")
        if hh_clusters.empty:
            return None

        trajectory = []
        for _, row in hh_clusters.iterrows():
            cid = int(row["aligned_cluster_label"])
            trajectory.append({
                "window_id": str(row["window_id"]),
                "cluster_id": cid,
                "cluster_label": CLUSTER_LABELS.get(cid, f"Cluster {cid}"),
                "window_role": str(row.get("window_role", "analysis")),
            })

        current_cid = trajectory[-1]["cluster_id"]
        return {
            "household_id": household_id,
            "trajectory": trajectory,
            "current_cluster_id": current_cid,
            "current_cluster_label": CLUSTER_LABELS.get(current_cid, f"Cluster {current_cid}"),
        }

    def get_household_instability(self, household_id: str) -> Optional[Dict[str, Any]]:
        """Return instability series and reliability indicator matching Blueprint v2 §F.4."""
        inst = self.get_instability_volatility()
        if inst.empty:
            return None

        hh_inst = inst[inst["household_id"] == household_id].sort_values("window_id")
        if hh_inst.empty:
            return None

        series = []
        for _, row in hh_inst.iterrows():
            score = float(row["instability"])
            rel = "stable" if score <= 0.25 else ("moderate" if score <= 0.60 else "elevated_risk")
            series.append({
                "window_id": str(row["window_id"]),
                "instability": round(score, 3),
                "volatility_cv": round(float(row["volatility_cv"]), 3),
                "reliability": rel,
            })

        latest_score = series[-1]["instability"]
        rel_indicator = "stable" if latest_score <= 0.25 else ("moderate" if latest_score <= 0.60 else "elevated_risk")

        return {
            "household_id": household_id,
            "series": series,
            "reliability_indicator": rel_indicator,
        }

    def get_household_anomaly(self, household_id: str) -> Optional[Dict[str, Any]]:
        """Return anomaly flags and explanations matching Blueprint v2 §F.5."""
        anom = self.get_anomaly_flags()
        if anom.empty:
            return None

        hh_anom = anom[anom["household_id"] == household_id].sort_values("window_id")
        if hh_anom.empty:
            return None

        flags = []
        for _, row in hh_anom.iterrows():
            flags.append({
                "window_id": str(row["window_id"]),
                "is_anomaly": bool(row["is_anomaly"]),
                "anomaly_score": float(row.get("anomaly_score", 0.0)),
                "triggering_statistic": str(row.get("triggering_statistic", "normal")),
                "value": float(row.get("value", 0.0)),
                "baseline_mean": float(row.get("baseline_mean", 0.0)),
                "baseline_std": float(row.get("baseline_std", 0.0)),
                "z_score": float(row.get("z_score", 0.0)),
                "severity": str(row.get("severity", "normal")),
                "explanation": str(row.get("explanation", "")),
            })

        return {
            "household_id": household_id,
            "flags": flags,
        }

    def get_household_forecast(
        self,
        household_id: str,
        window_id: Optional[str] = None,
        sample_step: int = 1,
    ) -> Optional[Dict[str, Any]]:
        """Return half-hourly load forecast series matching Blueprint v2 §F.2."""
        summary_df = self.get_forecast_global_summary()
        percluster_summary_df = self.get_forecast_percluster_summary()

        if summary_df.empty:
            return None

        hh_summary = summary_df[summary_df["household_id"] == household_id]
        if hh_summary.empty:
            return None

        # Resolve window_id
        if window_id is None:
            window_id = hh_summary["window_id"].max()

        row_match = hh_summary[hh_summary["window_id"] == window_id]
        if row_match.empty:
            return None

        mae_global = float(row_match.iloc[0]["ae"])

        # Percluster MAE
        mae_percluster = mae_global
        if not percluster_summary_df.empty:
            pc_match = percluster_summary_df[
                (percluster_summary_df["household_id"] == household_id) &
                (percluster_summary_df["window_id"] == window_id)
            ]
            if not pc_match.empty:
                mae_percluster = float(pc_match.iloc[0]["ae"])

        # Fetch series via PyArrow pushdown filters
        fc_global_path = self.artifacts_dir / "forecast_global.parquet"
        fc_pc_path = self.artifacts_dir / "forecast_percluster.parquet"

        series = []
        if fc_global_path.exists():
            try:
                g_df = pd.read_parquet(
                    fc_global_path,
                    filters=[[("household_id", "==", household_id), ("window_id", "==", window_id)]],
                )
                if not g_df.empty:
                    # Optional join with percluster
                    pc_dict = {}
                    if fc_pc_path.exists():
                        pc_df = pd.read_parquet(
                            fc_pc_path,
                            filters=[[("household_id", "==", household_id), ("window_id", "==", window_id)]],
                        )
                        if not pc_df.empty:
                            pc_dict = dict(zip(pc_df["slot_index"], pc_df["predicted"]))

                    # Build series (apply sample step if large)
                    g_df = g_df.sort_values("slot_index").iloc[::sample_step]
                    for _, r in g_df.iterrows():
                        slot = int(r["slot_index"])
                        pred_g = float(r["predicted"])
                        pred_pc = float(pc_dict.get(slot, pred_g))
                        day_str = str(r.get("day", ""))
                        hh_num = int(r.get("half_hour", slot % 48))
                        hour = hh_num // 2
                        minute = 30 if hh_num % 2 == 1 else 0
                        ts = f"{day_str}T{hour:02d}:{minute:02d}:00" if day_str else f"Slot_{slot}"

                        series.append({
                            "slot_index": slot,
                            "timestamp": ts,
                            "actual": float(r["actual"]),
                            "predicted_global": round(pred_g, 4),
                            "predicted_percluster": round(pred_pc, 4),
                        })
            except Exception as e:
                logger.warning(f"Could not load forecast series for {household_id} {window_id}: {e}")

        # Fetch SHAP top features
        shap_top_features = []
        shap_df = self.get_shap_explanations()
        if not shap_df.empty:
            hh_shap = shap_df[
                (shap_df["household_id"] == household_id) &
                (shap_df["window_id"] == window_id)
            ]
            if not hh_shap.empty:
                shap_cols = [c for c in hh_shap.columns if c.startswith("shap_")]
                mean_contribs = hh_shap[shap_cols].abs().mean().sort_values(ascending=False)
                for col, val in mean_contribs.items():
                    feat_name = col.replace("shap_", "")
                    shap_top_features.append({
                        "feature": feat_name,
                        "contribution": round(float(val), 4),
                    })

        # Fallback default features if none recorded for this specific slot
        if not shap_top_features:
            shap_top_features = [
                {"feature": "mean_load", "contribution": 0.12},
                {"feature": "half_hour", "contribution": 0.08},
                {"feature": "std_load", "contribution": 0.03},
                {"feature": "peak_load", "contribution": 0.01},
            ]

        return {
            "household_id": household_id,
            "window_id": window_id,
            "series": series,
            "mae_global": round(mae_global, 4),
            "mae_percluster": round(mae_percluster, 4),
            "shap_top_features": shap_top_features,
        }


# Global singleton instance
store = ArtifactStore()
